### ISSUE TITLE
[feature request] Multiple workloads in one deploy

### ISSUE THREAD

**Issue by williamoverton** [score-spec/score-humanitec#34]
**Is your feature request related to a problem? Please describe.**

When deploying an app with multiple workloads each with individual score files it is common that you would want to deploy two workloads at the same time as a single release. This is very possible with helm charts but currently not possible with score-humanitec.

**Describe the solution you'd like**
I would like a change to the score spec which allows for an index.score.yaml file which could include content such as:

```
uses:
  - ./frontend/score.yaml
  - ./backend/score.yaml
```

when calling `score-humanitec ... index.score.yaml` the index file would be evaluated as each entry being its own workload

**Describe alternatives you've considered**

A solution which does not involve changing the spec would be to have score-humanitec be able to append onto existing drafts.

so I could do something like:

```
score-humanitec --app demo create-draft --id "my-draft"
cd frontend && score-humanitec delta --draft-id "my-draft"
cd ../backend && score-humanitec delta --draft-id "my-draft"
score-humanitec deploy-draft --id "my-draft"
```

This is probably a nice feature to have but for ease of use for a developer I prefer the index file version. 

**Additional context**

I am basing my experience from a mono repo stack I am currently working on with multiple workloads in a single repo separated into folders e.g. ./frontend and ./backend etc.

**Comment by ghen** [comment]
Humanitec API supports an option to patch existing delta. So we can pick one of the following approaches to solve the problem:

- Use `score-humanitec` to produce multiple delta JSON files and apply and deploy those with Humanitec CLI tool
- Update `score-humanitec` CLI to accept `delta_id` when creating a draft. If `delta_id` is provided, then it would apply changes to existent draft rather than creating a new one.
- Update `score-humanitec` to accept multiple input files, merge those on the fly, and create a new combined draft

### Use `score-humanitec` to produce delta JSON only

This is the most robust option, and moving forward, should be the goal implementation.

With this approach `score-humanitec` CLI tool would act in exactly the same way, as other tools, such as `score-compose` or `score-helm`. E.g. it would only validate and convert the Score spec into a format, digestible by the target platform orchestrator toolkit. And other CLI tools then can be used to handle the deployment (similar to `compose` and `helm` CLI tools).

In this case the User can convert multiple Score specs into JSON files, combine and review them, and deploy with Humanitec CLI tool.

Another important benefit here that we do not need to implement, test, and maintain Humanitec API support in `score-humanitec` code base, as it is already implemented by Humanitec CLI tool.

### Update `score-humanitec` CLI to accept `delta_id`

This option could be used as a short term workaround for the problem.

With this approach the User would create a new delta with the very first Score spec. And all other Score specs can be added into existent delta. At the the end the delta can be revived or deployed.

### Update `score-humanitec` to accept multiple input files

In this scenario the User would feed multiple score spec files to `score-humanitec` tool. Something like this:

```
score-humanitec draft -f worload-a.yaml -f workload-b.yaml
```

The problem with this approach, however, is that each source Score spec can have one or more additional extensions files that needs to be included. And sourcing many dependant files could be tricky and lead to frequent mistakes.

**Comment by johanneswuerbach** [comment]
I think before looking at solutions, we should validate whether a similar problem exists in score-compose / score-helm as that likely affects the path forward.

We frequently have the case that multiple workloads (with the same image) are defined in one repository and are being developed together.

In those cases the compose file often looks like:

```yaml
services:
  http:
    image: awesome/service
    command: bin/server

  consumer:
    image: awesome/service
    command: bin/consumer
```

Achieving this with score-compose today is rather complicated and requires multiple overrides, hence I think the same problem exists there (and probably also in score-helm).

Therefor I think any `score-humanitec` specific solution isn't ideal and we should look for something that is applicable to all implementations.

Looking at the multiple input files solution:

> The problem with this approach, however, is that each source Score spec can have one or more additional extensions files that needs to be included.

Isn't the main problem here that overrides currently aren't defining explicitly which workload they reference? Which could be solved by required overrides to define a that?
```
metadata:
  name: web-app
```

**Comment by nickhumanitec** [comment]
This is probably Humanitec specific

Consider two workloads:
```
score-humanitec -f backend.yaml
wait_for_humanitec_deployment
score-humanitec -f frontend.yaml
```

If the frontend deployment fails (say wrong property), then running these commands in the same order will render the same error. backend will deployed (again), and it won't succeed because the frontend deployment will fail the same way it did before.

This is tricky, as a developer I would need to orchestrate and test if deployment succeeded, otherwise just re-deploy broken ones, before I can keep deploying and fix my pipeline.

**Comment by astromechza** [comment]
I've merged in the above PR which adds a `--delta` flag to pass in the ID of an existing delta and merge the results together. This should go a long way towards supporting multiple workloads in one deploy by allowing it to be built in multiple steps.

This hasn't _yet_ been released, but it is merged to main. Documentation in the docs site will be made available.
